- hosts: clientserver
  sudo: yes
  vars:
    - apt_file: /etc/apt/sources.list.d/google-chrome.list
  tasks:
  - name: Update apt-get repo and cache
    apt: update_cache=yes cache_valid_time=3600
  - name: Create a login user
    user:
      name: ruslan
      password: '$6$FDjlgpcjyhJsxi4a$ejnEc4MQ4z0IozDmnhThd0oC2cPBMka1jyL3Dh1XMmAplUnrqZ0I1wYyj5rYb4TehvLQjBCmwKAV2GYCUJy.D0'
      update_password: on_create
      groups: sudo
      state: present
      shell: /bin/bash
      system: no
      createhome: yes
      home: /home/ruslanas
  - name: Does the Google apt file exist?
    command: test -f {{apt_file}}
    register: google_apt_exists
    ignore_errors: True
  - name: Add Google Chrome key
    shell: wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
    when: google_apt_exists.rc == 1
  - name: Add Google Chrome repo  
    copy: content="deb http://dl.google.com/linux/chrome/deb/ stable main" dest={{apt_file}} owner=root group=root mode=644
    when: google_apt_exists.rc == 1                       
  - name: Update apt cache
    apt: update_cache=yes
    when: google_apt_exists.rc == 1
  - name: Install Google Chrome
    apt: pkg=google-chrome-stable state=latest
