- hosts: webserver
  sudo: yes
  tasks:
  - name: Update apt-get repo and cache
    apt: update_cache=yes
         cache_valid_time=3600
  - name: Upgrade all apt packages
    apt: upgrade=dist
  - name: Install apache
    apt: name=apache2   
         update_cache=yes    
         state=latest
  - name: Install git        
    apt: name=git
         update_cache=yes
         state=latest         
  - name: Install all required packages
    apt: name={{ item }} update_cache=yes state=latest
    with_items:
      - php5-cli
      - php5
      - libapache2-mod-php5
      - php5-fpm      
      - php5-intl
      - php5-json        
      - php5-mcrypt
      - mysql-server
      - mysql-client
      - php5-mysql        
      - python-mysqldb     
  - name: Delete files from /var/www/html
    file:     
      path: /var/www/html/index.html
      state: absent
  - name: Clone git repository   
    git:
      dest: /var/www/html
      repo: https://github.com/G-Ruslanas/Hospital.git                                                                                
  - name: Restart apache2
    service: name=apache2
             state=restarted